### ISSUE TITLE
[Suggestion] Would it be possible to update to Harmony v1.1.0?

### ISSUE THREAD

**Issue by cgodo** [zeobviouslyfakeacc/ModLoaderInstaller#12] opened 2018-07-13 16:41 UTC
Hi,

Harmony v1.1.0 includes some nice features that would be nice to have. Is it complicated to update this to work with latest version of Harmony?

Many thanks!

**Comment by zeobviouslyfakeacc** [comment] 2018-07-13 17:59
I'll have to test whether this version of Harmony is backwards compatible to the one we're currently using.

If it is, there's no reason not to update. I'll try to get an update for the Mod Loader out some time soon™️.

However, keep in mind that since the mod loader usually keeps working for long periods of time, people rarely install updates, so it will take some time until the new version of Harmony is widely adopted.

**Comment by zeobviouslyfakeacc** [comment] 2018-07-18 12:46
I have some bad news: due to an earlier mistake on my part, the new version of Harmony isn't even remotely backwards compatible.

Essentially, I can make old mods compiled with Harmony v.1.0.9.1 run on new installs with Harmony v1.1, but mods compiled with Harmony v1.1 will not even load on the current version of the mod loader.

Even worse, there's currently no indication that this is caused by having an outdated version of the mod loader. I'm afraid that if I were to release this update with the new version of Harmony, people would just complain to the mod authors, even though this isn't a problem they can fix.

To make sure something like that can't happen again in the future, I've added an [automated update checker](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/commit/353dbe5126b0f351ab03e07e24eff080d64aede2) to at least notify players that there's a new version of the mod loader.

But for the time being, I think it would be best to wait at least until Episode 3 is released.
I'm hoping that that update will also include a new version of the input library Rewired that the mod loader hooks into, breaking the mod loader in the process.

That way, the only version of the mod loader that will work with that new game update will be the version that includes Harmony v1.1, so I won't have to worry about backwards compatibility.

Sorry about the delay.

**Comment by zeobviouslyfakeacc** [comment] 2018-12-21 16:17
As expected, the recent v1.41 update has shipped with a newer version of Rewired, which has broken the mod loader, which **finally** gave us a chance to cleanly update Harmony! [Version 1.4](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.4) has been released with [Harmony v1.2.0.1](https://github.com/pardeike/Harmony/releases/tag/v1.2.0.1) 🎉

It might be worth separating Harmony updates from the rest of the mod loader - I'll look into that at a later date 😄

**Closed as completed by zeobviouslyfakeacc** 2018-12-21 16:17 UTC
Labels: enhancement
