### ISSUE TITLE
No longer working with TLD 1.27

### ISSUE THREAD

**Issue by HumbleSage0** [zeobviouslyfakeacc/ModLoaderInstaller#9] opened 2018-03-21 15:45 UTC
Browsing to tld.exe or Rewired_Core.dll returns red "Invalid". Please update. Thanks for all your great work!

**Comment by zeobviouslyfakeacc** [comment] 2018-03-21 15:53
Duplicate of #8 

I'm just giving it the final touch and doing some QA on Linux. Check back in an hour or two :smile:

**Comment by HumbleSage0** [comment] 2018-03-21 16:02
Awesome! Thanks so much for the fast reply. Wasn’t sure if it was the same so sorry for the duplicate (versions were different). 😊

**Comment by zeobviouslyfakeacc** [comment] 2018-03-21 17:56
[Done](https://github.com/zeobviouslyfakeacc/ModLoaderInstaller/releases/tag/v1.3)! :smile:

Please let me know if anything doesn't work :blush:

**Closed as completed by zeobviouslyfakeacc** 2018-03-21 17:56 UTC

**Comment by HumbleSage0** [comment] 2018-03-21 19:49
Working like a champ! Thanks so much for doing it so quickly! 😊
